;; -*- lexical-binding: t -*-
;;; `early-config' --- Summary: Early rational-emacs config
;;; Commentary: This file is automatically generated from org-mode
;;; Code:

(add-to-list 'load-path (expand-file-name "modules" rational-config-path))
